// Orval config: generates typed API client (react-query) from docs/openapi.yaml.
// Run: `npm run generate:api` from the package root (frontend/1st/ai-pto-frontend).
//
// Output layout (tags mode): src/shared/api/{auth,objects,packages,documents,
// findings,checklist,reports}.ts + shared models in src/shared/api/model/.
// Handwritten files (client.ts, endpoints.ts, hooks.ts, orval-mutator.ts) are
// protected via the `clean` exclude patterns below.

import { defineConfig } from 'orval'

export default defineConfig({
  ptoApi: {
    input: '../../../docs/openapi.yaml',
    output: {
      target: './src/shared/api',
      schemas: './src/shared/api/model',
      mode: 'tags',
      client: 'react-query',
      httpClient: 'axios',
      clean: [
        '!client.ts',
        '!endpoints.ts',
        '!hooks.ts',
        '!orval-mutator.ts',
        '!index.ts',
      ],
      // NOTE: prettier is run explicitly in the `generate:api` npm script -
      // orval's built-in prettier step cannot spawn prettier.cmd on Windows.
      prettier: false,
      override: {
        // Short header instead of the default one that copies the whole
        // info.description block from the spec into every generated file.
        // Must return an array: orval wraps it in a /** */ comment and
        // concatenates it with a newline (plain strings get glued to imports).
        header: () => ['Generated by orval - do not edit manually'],
        mutator: {
          path: './src/shared/api/orval-mutator.ts',
          name: 'orvalInstance',
        },
        query: {
          useQuery: true,
          useMutation: true,
          useSuspenseQuery: false,
          shouldExportQueryKey: true,
          shouldExportHooks: true,
        },
      },
    },
  },
})
