/**
 * Generated by orval - do not edit manually
 */
import type { User } from './user'

export interface AuthResponse {
  accessToken: string
  /** Время жизни токена */
  expiresIn: number
  user: User
}
