/**
 * Generated by orval - do not edit manually
 */
import type { FindingStatus } from './findingStatus'

export type BulkUpdateFindingsBody = {
  /**
   * @minItems 1
   * @maxItems 500
   */
  ids: string[]
  status: FindingStatus
  comment?: string
}
