/**
 * Generated by orval - do not edit manually
 */
import type { ChecklistItem } from './checklistItem'

export interface Checklist {
  /**
   * @minimum 0
   * @maximum 1
   */
  readiness: number
  items: ChecklistItem[]
}
