/**
 * Generated by orval - do not edit manually
 */

export type ChecklistStatus = (typeof ChecklistStatus)[keyof typeof ChecklistStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChecklistStatus = {
  ok: 'ok',
  partial: 'partial',
  missing: 'missing',
} as const
