/**
 * Generated by orval - do not edit manually
 */
import type { DocumentType } from './documentType'
import type { ChecklistStatus } from './checklistStatus'

export interface ChecklistItem {
  documentType: DocumentType
  title: string
  /**
   * Сколько документов требуется
   * @minimum 0
   */
  required: number
  /**
   * Сколько найдено
   * @minimum 0
   */
  found: number
  status: ChecklistStatus
  documentIds: string[]
}
