/**
 * Generated by orval - do not edit manually
 */
import type { SeverityCounts } from './severityCounts'
import type { ConstructionObjectAllOfLastCheckedAt } from './constructionObjectAllOfLastCheckedAt'

export type ConstructionObjectAllOf = {
  id: string
  /**
   * Готовность пакета документов, доля от 0 до 1
   * @minimum 0
   * @maximum 1
   */
  readiness: number
  findings: SeverityCounts
  lastCheckedAt?: ConstructionObjectAllOfLastCheckedAt
  createdAt: string
}
