/**
 * Generated by orval - do not edit manually
 */
import type { ObjectInput } from './objectInput'
import type { ConstructionObjectAllOf } from './constructionObjectAllOf'

export type ConstructionObject = ObjectInput & ConstructionObjectAllOf
