/**
 * Generated by orval - do not edit manually
 */

/**
 * needs_ocr: в файле нет текстового слоя (скан), на первом этапе не обрабатывается
 */
export type DocumentStatus = (typeof DocumentStatus)[keyof typeof DocumentStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DocumentStatus = {
  queued: 'queued',
  processing: 'processing',
  done: 'done',
  failed: 'failed',
  needs_ocr: 'needs_ocr',
} as const
