/**
 * Generated by orval - do not edit manually
 */

export type DocumentStageEventType =
  (typeof DocumentStageEventType)[keyof typeof DocumentStageEventType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DocumentStageEventType = {
  documentstage: 'document.stage',
} as const
