/**
 * Generated by orval - do not edit manually
 */
import type { Document } from './document'
import type { DocumentDetailAllOf } from './documentDetailAllOf'

export type DocumentDetail = Document & DocumentDetailAllOf
