/**
 * Generated by orval - do not edit manually
 */
import type { DocumentPageCount } from './documentPageCount'
import type { DocumentType } from './documentType'
import type { DocumentTypeConfidence } from './documentTypeConfidence'
import type { DocumentStatus } from './documentStatus'
import type { DocumentStages } from './documentStages'
import type { SeverityCounts } from './severityCounts'

export interface Document {
  id: string
  objectId: string
  packageId: string
  fileName: string
  mimeType: string
  sizeBytes: number
  /** Для PDF; для XLSX число листов */
  pageCount?: DocumentPageCount
  type: DocumentType
  /**
   * @minimum 0
   * @maximum 1
   */
  typeConfidence?: DocumentTypeConfidence
  typeEditedManually?: boolean
  status: DocumentStatus
  /** Состояние каждого этапа обработки */
  stages: DocumentStages
  findings: SeverityCounts
  createdAt: string
}
