/**
 * Generated by orval - do not edit manually
 */

/**
 * Порядок значений отражает приоритет разбора по частоте у реального инженера ПТО
(интервью, 09.2026): АОСР → общий журнал работ → исполнительные схемы → журнал
бетонных работ → журнал сварочных работ → паспорта материалов → журнал входного
контроля → протоколы испытаний → журнал авторского надзора. Первый вертикальный
срез (Rule Engine, парсер) делается на `aosr` и `general_work_log`, следующий шаг —
`as_built_scheme` (требует поддержки DWG, см. открытые вопросы) и `concrete_log`.

aosr: акт освидетельствования скрытых работ; general_work_log: общий журнал работ
(СК-6); as_built_scheme: исполнительная схема (монтажная, геодезическая);
concrete_log: журнал бетонных работ; welding_log: журнал сварочных работ;
material_passport: паспорт качества или сертификат соответствия материала;
incoming_control_log: журнал входного контроля материалов; test_report: протокол
испытаний или экспертизы; author_supervision_log: журнал авторского надзора;
unknown: тип не определён.

 */
export type DocumentType = (typeof DocumentType)[keyof typeof DocumentType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DocumentType = {
  aosr: 'aosr',
  general_work_log: 'general_work_log',
  as_built_scheme: 'as_built_scheme',
  concrete_log: 'concrete_log',
  welding_log: 'welding_log',
  material_passport: 'material_passport',
  incoming_control_log: 'incoming_control_log',
  test_report: 'test_report',
  author_supervision_log: 'author_supervision_log',
  other: 'other',
  unknown: 'unknown',
} as const
