/**
 * Generated by orval - do not edit manually
 */
import type { StageState } from './stageState'

/**
 * Состояние каждого этапа обработки
 */
export type DocumentStages = {
  extract?: StageState
  classify?: StageState
  parse?: StageState
  rules?: StageState
  explain?: StageState
  report?: StageState
}
