/**
 * Generated by orval - do not edit manually
 */
import type { DocumentStageEventType } from './documentStageEventType'
import type { Stage } from './stage'
import type { StageStatus } from './stageStatus'
import type { StageError } from './stageError'

export interface DocumentStageEvent {
  type: DocumentStageEventType
  documentId: string
  stage: Stage
  status: StageStatus
  error?: StageError
}
