/**
 * Generated by orval - do not edit manually
 */
import type { ExtractedField } from './extractedField'

export type DocumentDetailAllOf = {
  fields: ExtractedField[]
  /**
   * Поля с уверенностью ниже порога интерфейс подсвечивает
   * @minimum 0
   * @maximum 1
   */
  lowConfidenceThreshold?: number
}
