/**
 * Generated by orval - do not edit manually
 */
import type { ErrorDetailsItem } from './errorDetailsItem'

export interface Error {
  /** Машинный код ошибки */
  code: string
  /** Понятное человеку описание, что случилось и что делать */
  message: string
  details?: ErrorDetailsItem[]
}
