/**
 * Generated by orval - do not edit manually
 */
import type { ExtractedFieldValue } from './extractedFieldValue'
import type { SourceRef } from './sourceRef'
import type { ExtractedFieldOriginalValue } from './extractedFieldOriginalValue'

export interface ExtractedField {
  key: string
  label: string
  value: ExtractedFieldValue
  /**
   * @minimum 0
   * @maximum 1
   */
  confidence: number
  source?: SourceRef
  editedManually: boolean
  /** Значение до ручной правки */
  originalValue?: ExtractedFieldOriginalValue
}
