/**
 * Generated by orval - do not edit manually
 */
import type { Severity } from './severity'
import type { FindingExplanation } from './findingExplanation'
import type { FindingExpected } from './findingExpected'
import type { FindingActual } from './findingActual'
import type { NormRef } from './normRef'
import type { SourceRef } from './sourceRef'
import type { FindingStatus } from './findingStatus'
import type { FindingComment } from './findingComment'
import type { FindingDecidedBy } from './findingDecidedBy'
import type { FindingDecidedAt } from './findingDecidedAt'

export interface Finding {
  id: string
  objectId: string
  documentId: string
  packageId: string
  ruleId: string
  ruleVersion: string
  severity: Severity
  /** Строгий результат правила, всегда заполнен */
  message: string
  /** Пояснение простым языком от LLM, может отсутствовать */
  explanation?: FindingExplanation
  expected?: FindingExpected
  actual?: FindingActual
  normRef?: NormRef
  sources: SourceRef[]
  /**
   * @minimum 0
   * @maximum 1
   */
  confidence: number
  status: FindingStatus
  comment?: FindingComment
  decidedBy?: FindingDecidedBy
  decidedAt?: FindingDecidedAt
  createdAt: string
  updatedAt: string
}
