/**
 * Generated by orval - do not edit manually
 */
import type { FindingStatus } from './findingStatus'
import type { FindingHistoryEntryComment } from './findingHistoryEntryComment'

export interface FindingHistoryEntry {
  at: string
  userId: string
  fromStatus: FindingStatus
  toStatus: FindingStatus
  comment?: FindingHistoryEntryComment
}
