/**
 * Generated by orval - do not edit manually
 */

/**
 * Открыто, принято (в отчёт подрядчику), отклонено (ложное срабатывание), исправлено
 */
export type FindingStatus = (typeof FindingStatus)[keyof typeof FindingStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FindingStatus = {
  open: 'open',
  accepted: 'accepted',
  dismissed: 'dismissed',
  fixed: 'fixed',
} as const
