/**
 * Generated by orval - do not edit manually
 */
import type { PageParameter } from './pageParameter'
import type { PageSizeParameter } from './pageSizeParameter'
import type { Severity } from './severity'
import type { FindingStatus } from './findingStatus'
import type { DocumentType } from './documentType'
import type { ListFindingsSort } from './listFindingsSort'

export type ListFindingsParams = {
  /**
   * @minimum 1
   */
  page?: PageParameter
  /**
   * @minimum 1
   * @maximum 200
   */
  pageSize?: PageSizeParameter
  severity?: Severity[]
  status?: FindingStatus[]
  documentId?: string
  documentType?: DocumentType
  ruleId?: string
  /**
   * По умолчанию берётся последний пакет
   */
  packageId?: string
  /**
   * Поиск по тексту замечания
   */
  q?: string
  sort?: ListFindingsSort
}
