/**
 * Generated by orval - do not edit manually
 */

export type ListDocumentsSort = (typeof ListDocumentsSort)[keyof typeof ListDocumentsSort]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListDocumentsSort = {
  fileName: 'fileName',
  '-fileName': '-fileName',
  createdAt: 'createdAt',
  '-createdAt': '-createdAt',
  findings: 'findings',
  '-findings': '-findings',
} as const
