/**
 * Generated by orval - do not edit manually
 */
import type { Document } from './document'
import type { PageMeta } from './pageMeta'

export type ListDocuments200 = {
  items: Document[]
  meta: PageMeta
}
