/**
 * Generated by orval - do not edit manually
 */
import type { SeverityCounts } from './severityCounts'
import type { ListFindings200CountsByStatus } from './listFindings200CountsByStatus'

/**
 * Счётчики по текущим фильтрам, кроме серьёзности и статуса (для переключателей в интерфейсе)
 */
export type ListFindings200Counts = {
  bySeverity?: SeverityCounts
  byStatus?: ListFindings200CountsByStatus
}
