/**
 * Generated by orval - do not edit manually
 */
import type { PageParameter } from './pageParameter'
import type { PageSizeParameter } from './pageSizeParameter'
import type { DocumentType } from './documentType'
import type { DocumentStatus } from './documentStatus'
import type { ListDocumentsSort } from './listDocumentsSort'

export type ListDocumentsParams = {
  /**
   * @minimum 1
   */
  page?: PageParameter
  /**
   * @minimum 1
   * @maximum 200
   */
  pageSize?: PageSizeParameter
  /**
   * По умолчанию берётся последний пакет
   */
  packageId?: string
  type?: DocumentType
  status?: DocumentStatus
  /**
   * Поиск по имени файла
   */
  q?: string
  sort?: ListDocumentsSort
}
