/**
 * Generated by orval - do not edit manually
 */
import type { Finding } from './finding'
import type { PageMeta } from './pageMeta'
import type { ListFindings200Counts } from './listFindings200Counts'

export type ListFindings200 = {
  items: Finding[]
  meta: PageMeta
  /** Счётчики по текущим фильтрам, кроме серьёзности и статуса (для переключателей в интерфейсе) */
  counts: ListFindings200Counts
}
