/**
 * Generated by orval - do not edit manually
 */

export type ListObjectsSort = (typeof ListObjectsSort)[keyof typeof ListObjectsSort]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListObjectsSort = {
  name: 'name',
  '-name': '-name',
  readiness: 'readiness',
  '-readiness': '-readiness',
  lastCheckedAt: 'lastCheckedAt',
  '-lastCheckedAt': '-lastCheckedAt',
} as const
