/**
 * Generated by orval - do not edit manually
 */
import type { ConstructionObject } from './constructionObject'
import type { PageMeta } from './pageMeta'

export type ListObjects200 = {
  items: ConstructionObject[]
  meta: PageMeta
}
