/**
 * Generated by orval - do not edit manually
 */
import type { PageParameter } from './pageParameter'
import type { PageSizeParameter } from './pageSizeParameter'
import type { ListObjectsSort } from './listObjectsSort'

export type ListObjectsParams = {
  /**
   * @minimum 1
   */
  page?: PageParameter
  /**
   * @minimum 1
   * @maximum 200
   */
  pageSize?: PageSizeParameter
  /**
   * Поиск по названию, адресу, подрядчику
   */
  q?: string
  sort?: ListObjectsSort
}
