/**
 * Generated by orval - do not edit manually
 */

export type ListFindingsSort = (typeof ListFindingsSort)[keyof typeof ListFindingsSort]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListFindingsSort = {
  severity: 'severity',
  '-severity': '-severity',
  confidence: 'confidence',
  '-confidence': '-confidence',
  createdAt: 'createdAt',
  '-createdAt': '-createdAt',
} as const
