/**
 * Generated by orval - do not edit manually
 */
import type { ObjectSummaryNextActionsItemKind } from './objectSummaryNextActionsItemKind'

export type ObjectSummaryNextActionsItem = {
  kind: ObjectSummaryNextActionsItemKind
  message: string
  count?: number
}
