/**
 * Generated by orval - do not edit manually
 */
import type { SeverityCounts } from './severityCounts'
import type { ObjectSummaryByDocumentTypeItem } from './objectSummaryByDocumentTypeItem'
import type { ObjectSummaryTopRulesItem } from './objectSummaryTopRulesItem'
import type { ObjectSummaryHistoryItem } from './objectSummaryHistoryItem'
import type { ObjectSummaryNextActionsItem } from './objectSummaryNextActionsItem'

export interface ObjectSummary {
  /**
   * @minimum 0
   * @maximum 1
   */
  readiness: number
  findings: SeverityCounts
  /**
   * Замечаний в статусе open
   * @minimum 0
   */
  pendingDecisions: number
  byDocumentType: ObjectSummaryByDocumentTypeItem[]
  topRules: ObjectSummaryTopRulesItem[]
  /** Динамика по проверкам (пакетам) */
  history?: ObjectSummaryHistoryItem[]
  nextActions?: ObjectSummaryNextActionsItem[]
}
