/**
 * Generated by orval - do not edit manually
 */
import type { SeverityCounts } from './severityCounts'

export type ObjectSummaryHistoryItem = {
  packageId: string
  version: number
  findings: SeverityCounts
  createdAt?: string
}
