/**
 * Generated by orval - do not edit manually
 */

export interface ObjectUpdate {
  /**
   * @minLength 1
   * @maxLength 200
   */
  name?: string
  address?: string
  customer?: string
  contractor?: string
  workTypeId?: string
}
