/**
 * Generated by orval - do not edit manually
 */

export type ObjectSummaryNextActionsItemKind =
  (typeof ObjectSummaryNextActionsItemKind)[keyof typeof ObjectSummaryNextActionsItemKind]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ObjectSummaryNextActionsItemKind = {
  missing_document: 'missing_document',
  pending_findings: 'pending_findings',
  failed_document: 'failed_document',
  needs_ocr: 'needs_ocr',
} as const
