/**
 * Generated by orval - do not edit manually
 */
import type { DocumentType } from './documentType'
import type { SeverityCounts } from './severityCounts'

export type ObjectSummaryByDocumentTypeItem = {
  documentType: DocumentType
  counts: SeverityCounts
}
