/**
 * Generated by orval - do not edit manually
 */

export interface ObjectInput {
  /**
   * @minLength 1
   * @maxLength 200
   */
  name: string
  address?: string
  /** Заказчик */
  customer?: string
  /** Подрядчик */
  contractor?: string
  workTypeId: string
}
