/**
 * Generated by orval - do not edit manually
 */

export type PackageProgressEventType =
  (typeof PackageProgressEventType)[keyof typeof PackageProgressEventType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PackageProgressEventType = {
  packageprogress: 'package.progress',
} as const
