/**
 * Generated by orval - do not edit manually
 */
import type { PackageCreateFilesItem } from './packageCreateFilesItem'

export interface PackageCreate {
  /**
   * @minItems 1
   * @maxItems 200
   */
  files: PackageCreateFilesItem[]
}
