/**
 * Generated by orval - do not edit manually
 */
import type { Package } from './package'
import type { PackageCreatedUploadsItem } from './packageCreatedUploadsItem'

export interface PackageCreated {
  package: Package
  uploads: PackageCreatedUploadsItem[]
}
