/**
 * Generated by orval - do not edit manually
 */

export type PackageCreateFilesItemMimeType =
  (typeof PackageCreateFilesItemMimeType)[keyof typeof PackageCreateFilesItemMimeType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PackageCreateFilesItemMimeType = {
  'application/pdf': 'application/pdf',
  'application/vndopenxmlformats-officedocumentwordprocessingmldocument':
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'application/vndopenxmlformats-officedocumentspreadsheetmlsheet':
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'text/csv': 'text/csv',
} as const
