/**
 * Generated by orval - do not edit manually
 */

export type PackageSnapshotEventType =
  (typeof PackageSnapshotEventType)[keyof typeof PackageSnapshotEventType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PackageSnapshotEventType = {
  packagesnapshot: 'package.snapshot',
} as const
