/**
 * Generated by orval - do not edit manually
 */
import type { Package } from './package'
import type { PackageDetailAllOf } from './packageDetailAllOf'

export type PackageDetail = Package & PackageDetailAllOf
