/**
 * Generated by orval - do not edit manually
 */

/**
 * partial означает, что часть документов не удалось обработать, остальные готовы
 */
export type PackageStatus = (typeof PackageStatus)[keyof typeof PackageStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PackageStatus = {
  uploading: 'uploading',
  queued: 'queued',
  processing: 'processing',
  done: 'done',
  partial: 'partial',
  failed: 'failed',
} as const
