/**
 * Generated by orval - do not edit manually
 */
import type { PackageCreatedUploadsItemUploadUrl } from './packageCreatedUploadsItemUploadUrl'
import type { PackageCreatedUploadsItemHeaders } from './packageCreatedUploadsItemHeaders'
import type { PackageCreatedUploadsItemDuplicateOf } from './packageCreatedUploadsItemDuplicateOf'

export type PackageCreatedUploadsItem = {
  documentId: string
  fileName: string
  /** Ссылка для PUT-загрузки. Пусто, если файл дубликат. */
  uploadUrl?: PackageCreatedUploadsItemUploadUrl
  /** Заголовки, которые нужно передать при загрузке */
  headers?: PackageCreatedUploadsItemHeaders
  expiresAt?: string
  /** Идентификатор уже загруженного документа с тем же хэшем */
  duplicateOf?: PackageCreatedUploadsItemDuplicateOf
}
