/**
 * Generated by orval - do not edit manually
 */
import type { PackageStatus } from './packageStatus'
import type { SeverityCounts } from './severityCounts'
import type { PackageFinishedAt } from './packageFinishedAt'

export interface Package {
  id: string
  objectId: string
  /**
   * Порядковый номер проверки на объекте
   * @minimum 1
   */
  version: number
  status: PackageStatus
  /**
   * @minimum 0
   * @maximum 1
   */
  progress: number
  /** @minimum 0 */
  documentsCount?: number
  findings?: SeverityCounts
  createdAt: string
  finishedAt?: PackageFinishedAt
}
