/**
 * Generated by orval - do not edit manually
 */
import type { PackageProgressEventType } from './packageProgressEventType'

export interface PackageProgressEvent {
  type: PackageProgressEventType
  /**
   * @minimum 0
   * @maximum 1
   */
  progress: number
}
