/**
 * Generated by orval - do not edit manually
 */
import type { PackageCreateFilesItemMimeType } from './packageCreateFilesItemMimeType'

export type PackageCreateFilesItem = {
  fileName: string
  mimeType: PackageCreateFilesItemMimeType
  /** @minimum 1 */
  sizeBytes: number
  /**
   * Хэш файла для дедупликации (необязательно)
   * @pattern ^[a-f0-9]{64}$
   */
  sha256?: string
}
