/**
 * Generated by orval - do not edit manually
 */

export type PackageDoneEventStatus =
  (typeof PackageDoneEventStatus)[keyof typeof PackageDoneEventStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PackageDoneEventStatus = {
  done: 'done',
  partial: 'partial',
  failed: 'failed',
} as const
