/**
 * Generated by orval - do not edit manually
 */
import type { PackageSnapshotEventType } from './packageSnapshotEventType'
import type { PackageDetail } from './packageDetail'

export interface PackageSnapshotEvent {
  type: PackageSnapshotEventType
  package: PackageDetail
}
