/**
 * Generated by orval - do not edit manually
 */

export type PackageDoneEventType = (typeof PackageDoneEventType)[keyof typeof PackageDoneEventType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PackageDoneEventType = {
  packagedone: 'package.done',
} as const
