/**
 * Generated by orval - do not edit manually
 */
import type { PackageDoneEventType } from './packageDoneEventType'
import type { PackageDoneEventStatus } from './packageDoneEventStatus'
import type { SeverityCounts } from './severityCounts'

export interface PackageDoneEvent {
  type: PackageDoneEventType
  status: PackageDoneEventStatus
  findings?: SeverityCounts
}
