/**
 * Generated by orval - do not edit manually
 */
import type { PackageSnapshotEvent } from './packageSnapshotEvent'
import type { DocumentStageEvent } from './documentStageEvent'
import type { PackageProgressEvent } from './packageProgressEvent'
import type { PackageDoneEvent } from './packageDoneEvent'

/**
 * Событие SSE. Поле `type` совпадает с именем события.
- `package.snapshot`: текущее состояние при подключении
- `document.stage`: изменился статус этапа документа
- `package.progress`: изменился общий прогресс
- `package.done`: обработка завершена (статус `done`, `partial` или `failed`)

 */
export type PackageEvent =
  PackageSnapshotEvent | DocumentStageEvent | PackageProgressEvent | PackageDoneEvent
