/**
 * Generated by orval - do not edit manually
 */

/**
 * Что включить, принятые замечания, только ошибки или все открытые
 */
export type ReportCreateScope = (typeof ReportCreateScope)[keyof typeof ReportCreateScope]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReportCreateScope = {
  accepted: 'accepted',
  errors: 'errors',
  all_open: 'all_open',
} as const
