/**
 * Generated by orval - do not edit manually
 */

export type ReportScope = (typeof ReportScope)[keyof typeof ReportScope]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReportScope = {
  accepted: 'accepted',
  errors: 'errors',
  all_open: 'all_open',
} as const
