/**
 * Generated by orval - do not edit manually
 */
import type { ReportStatus } from './reportStatus'
import type { ReportScope } from './reportScope'
import type { ReportRecipient } from './reportRecipient'
import type { StageError } from './stageError'
import type { ReportReadyAt } from './reportReadyAt'

export interface Report {
  id: string
  objectId: string
  packageId: string
  status: ReportStatus
  /** @minimum 1 */
  version: number
  scope?: ReportScope
  recipient?: ReportRecipient
  /** @minimum 0 */
  findingsCount?: number
  error?: StageError
  createdBy?: string
  createdAt: string
  readyAt?: ReportReadyAt
}
