/**
 * Generated by orval - do not edit manually
 */

export type ReportStatus = (typeof ReportStatus)[keyof typeof ReportStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReportStatus = {
  generating: 'generating',
  ready: 'ready',
  failed: 'failed',
} as const
