/**
 * Generated by orval - do not edit manually
 */
import type { ReportCreateScope } from './reportCreateScope'

export interface ReportCreate {
  /** Что включить, принятые замечания, только ошибки или все открытые */
  scope?: ReportCreateScope
  /** Кому адресован отчёт (подрядчик) */
  recipient?: string
}
