/**
 * Generated by orval - do not edit manually
 */

/**
 * Ошибка (не пройдёт приёмку), замечание (проверить вручную), сведения
 */
export type Severity = (typeof Severity)[keyof typeof Severity]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Severity = {
  error: 'error',
  warning: 'warning',
  info: 'info',
} as const
