/**
 * Generated by orval - do not edit manually
 */

/**
 * Место в файле, откуда взято значение. Для PDF заполняются `page` и `bbox`,
для XLSX `sheet` и `cell`, для DOCX `paragraph` или `table`.

 */
export interface SourceRef {
  documentId: string
  /**
   * Номер страницы PDF, с 1
   * @minimum 1
   */
  page?: number
  /**
   * [x0, y0, x1, y1] в долях страницы от верхнего левого угла
   * @minItems 4
   * @maxItems 4
   */
  bbox?: number[]
  sheet?: string
  cell?: string
  /** @minimum 0 */
  paragraph?: number
  /** Короткая цитата из источника */
  quote?: string
}
