/**
 * Generated by orval - do not edit manually
 */

export type StageStatus = (typeof StageStatus)[keyof typeof StageStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StageStatus = {
  pending: 'pending',
  running: 'running',
  done: 'done',
  failed: 'failed',
  skipped: 'skipped',
} as const
