/**
 * Generated by orval - do not edit manually
 */
import type { StageStatus } from './stageStatus'
import type { StageError } from './stageError'
import type { StageStateFinishedAt } from './stageStateFinishedAt'

export interface StageState {
  status: StageStatus
  error?: StageError
  finishedAt?: StageStateFinishedAt
}
