/**
 * Generated by orval - do not edit manually
 */

export type Stage = (typeof Stage)[keyof typeof Stage]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Stage = {
  extract: 'extract',
  classify: 'classify',
  parse: 'parse',
  rules: 'rules',
  explain: 'explain',
  report: 'report',
} as const
