/**
 * Generated by orval - do not edit manually
 */

export type StreamPackageEventsParams = {
  /**
   * Токен для клиентов, которые не могут задать заголовок Authorization
   */
  access_token?: string
}
