/**
 * Generated by orval - do not edit manually
 */
import type { UpdateDocumentFieldsBodyFieldsItem } from './updateDocumentFieldsBodyFieldsItem'

export type UpdateDocumentFieldsBody = {
  /** @minItems 1 */
  fields: UpdateDocumentFieldsBodyFieldsItem[]
}
