/**
 * Generated by orval - do not edit manually
 */
import type { UpdateDocumentFieldsBodyFieldsItemValue } from './updateDocumentFieldsBodyFieldsItemValue'

export type UpdateDocumentFieldsBodyFieldsItem = {
  key: string
  value: UpdateDocumentFieldsBodyFieldsItemValue
}
