/**
 * Generated by orval - do not edit manually
 */

export type UserRole = (typeof UserRole)[keyof typeof UserRole]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserRole = {
  engineer: 'engineer',
  contractor: 'contractor',
} as const
