/**
 * Generated by orval - do not edit manually
 */
import { useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type { Checklist, GetChecklistParams, NotFoundResponse, ObjectSummary } from './model'

import { orvalInstance } from './orval-mutator'

/**
 * Агрегаты для экрана «Обзор». На первом этапе фронтенд может считать их сам
из списка замечаний и комплектности, эндпоинт можно реализовать позже.

 * @summary Сводка по объекту (дашборд)
 */
export const getObjectSummary = (objectId: string, signal?: AbortSignal) => {
  return orvalInstance<ObjectSummary>({
    url: `/objects/${objectId}/summary`,
    method: 'GET',
    signal,
  })
}

export const getGetObjectSummaryQueryKey = (objectId?: string) => {
  return [`/objects/${objectId}/summary`] as const
}

export const getGetObjectSummaryQueryOptions = <
  TData = Awaited<ReturnType<typeof getObjectSummary>>,
  TError = NotFoundResponse,
>(
  objectId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getObjectSummary>>, TError, TData>>
  },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetObjectSummaryQueryKey(objectId)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getObjectSummary>>> = ({ signal }) =>
    getObjectSummary(objectId, signal)

  return { queryKey, queryFn, enabled: !!objectId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getObjectSummary>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetObjectSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof getObjectSummary>>>
export type GetObjectSummaryQueryError = NotFoundResponse

export function useGetObjectSummary<
  TData = Awaited<ReturnType<typeof getObjectSummary>>,
  TError = NotFoundResponse,
>(
  objectId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getObjectSummary>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getObjectSummary>>,
          TError,
          Awaited<ReturnType<typeof getObjectSummary>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetObjectSummary<
  TData = Awaited<ReturnType<typeof getObjectSummary>>,
  TError = NotFoundResponse,
>(
  objectId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getObjectSummary>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getObjectSummary>>,
          TError,
          Awaited<ReturnType<typeof getObjectSummary>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetObjectSummary<
  TData = Awaited<ReturnType<typeof getObjectSummary>>,
  TError = NotFoundResponse,
>(
  objectId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getObjectSummary>>, TError, TData>>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Сводка по объекту (дашборд)
 */

export function useGetObjectSummary<
  TData = Awaited<ReturnType<typeof getObjectSummary>>,
  TError = NotFoundResponse,
>(
  objectId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getObjectSummary>>, TError, TData>>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetObjectSummaryQueryOptions(objectId, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Сравнивает обязательные документы для вида работ с найденными в последнем пакете.
 * @summary Комплектность объекта
 */
export const getChecklist = (
  objectId: string,
  params?: GetChecklistParams,
  signal?: AbortSignal,
) => {
  return orvalInstance<Checklist>({
    url: `/objects/${objectId}/checklist`,
    method: 'GET',
    params,
    signal,
  })
}

export const getGetChecklistQueryKey = (objectId?: string, params?: GetChecklistParams) => {
  return [`/objects/${objectId}/checklist`, ...(params ? [params] : [])] as const
}

export const getGetChecklistQueryOptions = <
  TData = Awaited<ReturnType<typeof getChecklist>>,
  TError = NotFoundResponse,
>(
  objectId: string,
  params?: GetChecklistParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getChecklist>>, TError, TData>>
  },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetChecklistQueryKey(objectId, params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getChecklist>>> = ({ signal }) =>
    getChecklist(objectId, params, signal)

  return { queryKey, queryFn, enabled: !!objectId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getChecklist>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetChecklistQueryResult = NonNullable<Awaited<ReturnType<typeof getChecklist>>>
export type GetChecklistQueryError = NotFoundResponse

export function useGetChecklist<
  TData = Awaited<ReturnType<typeof getChecklist>>,
  TError = NotFoundResponse,
>(
  objectId: string,
  params: undefined | GetChecklistParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getChecklist>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChecklist>>,
          TError,
          Awaited<ReturnType<typeof getChecklist>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetChecklist<
  TData = Awaited<ReturnType<typeof getChecklist>>,
  TError = NotFoundResponse,
>(
  objectId: string,
  params?: GetChecklistParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getChecklist>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChecklist>>,
          TError,
          Awaited<ReturnType<typeof getChecklist>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetChecklist<
  TData = Awaited<ReturnType<typeof getChecklist>>,
  TError = NotFoundResponse,
>(
  objectId: string,
  params?: GetChecklistParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getChecklist>>, TError, TData>>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Комплектность объекта
 */

export function useGetChecklist<
  TData = Awaited<ReturnType<typeof getChecklist>>,
  TError = NotFoundResponse,
>(
  objectId: string,
  params?: GetChecklistParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getChecklist>>, TError, TData>>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetChecklistQueryOptions(objectId, params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}
