/**
 * Generated by orval - do not edit manually
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  Document,
  DocumentDetail,
  GetDocumentFile200,
  ListDocuments200,
  ListDocumentsParams,
  NotFoundResponse,
  RecheckDocumentBody,
  UpdateDocumentBody,
  UpdateDocumentFieldsBody,
  ValidationErrorResponse,
} from './model'

import { orvalInstance } from './orval-mutator'

/**
 * @summary Документы объекта
 */
export const listDocuments = (
  objectId: string,
  params?: ListDocumentsParams,
  signal?: AbortSignal,
) => {
  return orvalInstance<ListDocuments200>({
    url: `/objects/${objectId}/documents`,
    method: 'GET',
    params,
    signal,
  })
}

export const getListDocumentsQueryKey = (objectId?: string, params?: ListDocumentsParams) => {
  return [`/objects/${objectId}/documents`, ...(params ? [params] : [])] as const
}

export const getListDocumentsQueryOptions = <
  TData = Awaited<ReturnType<typeof listDocuments>>,
  TError = NotFoundResponse,
>(
  objectId: string,
  params?: ListDocumentsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listDocuments>>, TError, TData>>
  },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getListDocumentsQueryKey(objectId, params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listDocuments>>> = ({ signal }) =>
    listDocuments(objectId, params, signal)

  return { queryKey, queryFn, enabled: !!objectId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listDocuments>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListDocumentsQueryResult = NonNullable<Awaited<ReturnType<typeof listDocuments>>>
export type ListDocumentsQueryError = NotFoundResponse

export function useListDocuments<
  TData = Awaited<ReturnType<typeof listDocuments>>,
  TError = NotFoundResponse,
>(
  objectId: string,
  params: undefined | ListDocumentsParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listDocuments>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDocuments>>,
          TError,
          Awaited<ReturnType<typeof listDocuments>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListDocuments<
  TData = Awaited<ReturnType<typeof listDocuments>>,
  TError = NotFoundResponse,
>(
  objectId: string,
  params?: ListDocumentsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listDocuments>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDocuments>>,
          TError,
          Awaited<ReturnType<typeof listDocuments>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListDocuments<
  TData = Awaited<ReturnType<typeof listDocuments>>,
  TError = NotFoundResponse,
>(
  objectId: string,
  params?: ListDocumentsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listDocuments>>, TError, TData>>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Документы объекта
 */

export function useListDocuments<
  TData = Awaited<ReturnType<typeof listDocuments>>,
  TError = NotFoundResponse,
>(
  objectId: string,
  params?: ListDocumentsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listDocuments>>, TError, TData>>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListDocumentsQueryOptions(objectId, params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Метаданные, этапы обработки и извлечённые поля.
 * @summary Карточка документа
 */
export const getDocument = (documentId: string, signal?: AbortSignal) => {
  return orvalInstance<DocumentDetail>({ url: `/documents/${documentId}`, method: 'GET', signal })
}

export const getGetDocumentQueryKey = (documentId?: string) => {
  return [`/documents/${documentId}`] as const
}

export const getGetDocumentQueryOptions = <
  TData = Awaited<ReturnType<typeof getDocument>>,
  TError = NotFoundResponse,
>(
  documentId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocument>>, TError, TData>>
  },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetDocumentQueryKey(documentId)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDocument>>> = ({ signal }) =>
    getDocument(documentId, signal)

  return { queryKey, queryFn, enabled: !!documentId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDocument>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDocumentQueryResult = NonNullable<Awaited<ReturnType<typeof getDocument>>>
export type GetDocumentQueryError = NotFoundResponse

export function useGetDocument<
  TData = Awaited<ReturnType<typeof getDocument>>,
  TError = NotFoundResponse,
>(
  documentId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocument>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocument>>,
          TError,
          Awaited<ReturnType<typeof getDocument>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocument<
  TData = Awaited<ReturnType<typeof getDocument>>,
  TError = NotFoundResponse,
>(
  documentId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocument>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocument>>,
          TError,
          Awaited<ReturnType<typeof getDocument>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocument<
  TData = Awaited<ReturnType<typeof getDocument>>,
  TError = NotFoundResponse,
>(
  documentId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocument>>, TError, TData>>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Карточка документа
 */

export function useGetDocument<
  TData = Awaited<ReturnType<typeof getDocument>>,
  TError = NotFoundResponse,
>(
  documentId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocument>>, TError, TData>>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetDocumentQueryOptions(documentId, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Ручная смена типа запускает повторное извлечение полей и проверку правил.
 * @summary Изменить тип документа
 */
export const updateDocument = (documentId: string, updateDocumentBody: UpdateDocumentBody) => {
  return orvalInstance<Document>({
    url: `/documents/${documentId}`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: updateDocumentBody,
  })
}

export const getUpdateDocumentMutationOptions = <
  TError = NotFoundResponse | ValidationErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateDocument>>,
    TError,
    { documentId: string; data: UpdateDocumentBody },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateDocument>>,
  TError,
  { documentId: string; data: UpdateDocumentBody },
  TContext
> => {
  const mutationKey = ['updateDocument']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateDocument>>,
    { documentId: string; data: UpdateDocumentBody }
  > = (props) => {
    const { documentId, data } = props ?? {}

    return updateDocument(documentId, data)
  }

  return { mutationFn, ...mutationOptions }
}

export type UpdateDocumentMutationResult = NonNullable<Awaited<ReturnType<typeof updateDocument>>>
export type UpdateDocumentMutationBody = UpdateDocumentBody
export type UpdateDocumentMutationError = NotFoundResponse | ValidationErrorResponse

/**
 * @summary Изменить тип документа
 */
export const useUpdateDocument = <
  TError = NotFoundResponse | ValidationErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateDocument>>,
      TError,
      { documentId: string; data: UpdateDocumentBody },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateDocument>>,
  TError,
  { documentId: string; data: UpdateDocumentBody },
  TContext
> => {
  const mutationOptions = getUpdateDocumentMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Удалить документ
 */
export const deleteDocument = (documentId: string) => {
  return orvalInstance<void>({ url: `/documents/${documentId}`, method: 'DELETE' })
}

export const getDeleteDocumentMutationOptions = <
  TError = NotFoundResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteDocument>>,
    TError,
    { documentId: string },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteDocument>>,
  TError,
  { documentId: string },
  TContext
> => {
  const mutationKey = ['deleteDocument']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteDocument>>,
    { documentId: string }
  > = (props) => {
    const { documentId } = props ?? {}

    return deleteDocument(documentId)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteDocumentMutationResult = NonNullable<Awaited<ReturnType<typeof deleteDocument>>>

export type DeleteDocumentMutationError = NotFoundResponse

/**
 * @summary Удалить документ
 */
export const useDeleteDocument = <TError = NotFoundResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteDocument>>,
      TError,
      { documentId: string },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteDocument>>,
  TError,
  { documentId: string },
  TContext
> => {
  const mutationOptions = getDeleteDocumentMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Временная ссылка для просмотра или скачивания оригинала.
 * @summary Ссылка на исходный файл
 */
export const getDocumentFile = (documentId: string, signal?: AbortSignal) => {
  return orvalInstance<GetDocumentFile200>({
    url: `/documents/${documentId}/file`,
    method: 'GET',
    signal,
  })
}

export const getGetDocumentFileQueryKey = (documentId?: string) => {
  return [`/documents/${documentId}/file`] as const
}

export const getGetDocumentFileQueryOptions = <
  TData = Awaited<ReturnType<typeof getDocumentFile>>,
  TError = NotFoundResponse,
>(
  documentId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentFile>>, TError, TData>>
  },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetDocumentFileQueryKey(documentId)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDocumentFile>>> = ({ signal }) =>
    getDocumentFile(documentId, signal)

  return { queryKey, queryFn, enabled: !!documentId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDocumentFile>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDocumentFileQueryResult = NonNullable<Awaited<ReturnType<typeof getDocumentFile>>>
export type GetDocumentFileQueryError = NotFoundResponse

export function useGetDocumentFile<
  TData = Awaited<ReturnType<typeof getDocumentFile>>,
  TError = NotFoundResponse,
>(
  documentId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentFile>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocumentFile>>,
          TError,
          Awaited<ReturnType<typeof getDocumentFile>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocumentFile<
  TData = Awaited<ReturnType<typeof getDocumentFile>>,
  TError = NotFoundResponse,
>(
  documentId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentFile>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocumentFile>>,
          TError,
          Awaited<ReturnType<typeof getDocumentFile>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocumentFile<
  TData = Awaited<ReturnType<typeof getDocumentFile>>,
  TError = NotFoundResponse,
>(
  documentId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentFile>>, TError, TData>>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Ссылка на исходный файл
 */

export function useGetDocumentFile<
  TData = Awaited<ReturnType<typeof getDocumentFile>>,
  TError = NotFoundResponse,
>(
  documentId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentFile>>, TError, TData>>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetDocumentFileQueryOptions(documentId, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Изменённые поля помечаются `editedManually: true`, исходное значение сохраняется
в `originalValue`. После изменения запускается перепроверка связанных правил
(этап `rules` документа переходит в `running`).

 * @summary Исправить извлечённые поля
 */
export const updateDocumentFields = (
  documentId: string,
  updateDocumentFieldsBody: UpdateDocumentFieldsBody,
) => {
  return orvalInstance<DocumentDetail>({
    url: `/documents/${documentId}/fields`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: updateDocumentFieldsBody,
  })
}

export const getUpdateDocumentFieldsMutationOptions = <
  TError = NotFoundResponse | ValidationErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateDocumentFields>>,
    TError,
    { documentId: string; data: UpdateDocumentFieldsBody },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateDocumentFields>>,
  TError,
  { documentId: string; data: UpdateDocumentFieldsBody },
  TContext
> => {
  const mutationKey = ['updateDocumentFields']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateDocumentFields>>,
    { documentId: string; data: UpdateDocumentFieldsBody }
  > = (props) => {
    const { documentId, data } = props ?? {}

    return updateDocumentFields(documentId, data)
  }

  return { mutationFn, ...mutationOptions }
}

export type UpdateDocumentFieldsMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateDocumentFields>>
>
export type UpdateDocumentFieldsMutationBody = UpdateDocumentFieldsBody
export type UpdateDocumentFieldsMutationError = NotFoundResponse | ValidationErrorResponse

/**
 * @summary Исправить извлечённые поля
 */
export const useUpdateDocumentFields = <
  TError = NotFoundResponse | ValidationErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateDocumentFields>>,
      TError,
      { documentId: string; data: UpdateDocumentFieldsBody },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateDocumentFields>>,
  TError,
  { documentId: string; data: UpdateDocumentFieldsBody },
  TContext
> => {
  const mutationOptions = getUpdateDocumentFieldsMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Перезапускает указанные этапы (по умолчанию `rules`) и все последующие.
Результаты предыдущих этапов берутся из БД, LLM повторно не вызывается,
если это не требуется.

 * @summary Перезапустить обработку документа
 */
export const recheckDocument = (
  documentId: string,
  recheckDocumentBody?: RecheckDocumentBody,
  signal?: AbortSignal,
) => {
  return orvalInstance<Document>({
    url: `/documents/${documentId}/recheck`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: recheckDocumentBody,
    signal,
  })
}

export const getRecheckDocumentMutationOptions = <
  TError = NotFoundResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof recheckDocument>>,
    TError,
    { documentId: string; data: RecheckDocumentBody },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof recheckDocument>>,
  TError,
  { documentId: string; data: RecheckDocumentBody },
  TContext
> => {
  const mutationKey = ['recheckDocument']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof recheckDocument>>,
    { documentId: string; data: RecheckDocumentBody }
  > = (props) => {
    const { documentId, data } = props ?? {}

    return recheckDocument(documentId, data)
  }

  return { mutationFn, ...mutationOptions }
}

export type RecheckDocumentMutationResult = NonNullable<Awaited<ReturnType<typeof recheckDocument>>>
export type RecheckDocumentMutationBody = RecheckDocumentBody
export type RecheckDocumentMutationError = NotFoundResponse

/**
 * @summary Перезапустить обработку документа
 */
export const useRecheckDocument = <TError = NotFoundResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof recheckDocument>>,
      TError,
      { documentId: string; data: RecheckDocumentBody },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof recheckDocument>>,
  TError,
  { documentId: string; data: RecheckDocumentBody },
  TContext
> => {
  const mutationOptions = getRecheckDocumentMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
