/**
 * Generated by orval - do not edit manually
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  BulkUpdateFindings200,
  BulkUpdateFindingsBody,
  Finding,
  FindingHistoryEntry,
  FindingUpdate,
  ListFindings200,
  ListFindingsParams,
  NotFoundResponse,
  ValidationErrorResponse,
} from './model'

import { orvalInstance } from './orval-mutator'

/**
 * @summary Замечания объекта
 */
export const listFindings = (
  objectId: string,
  params?: ListFindingsParams,
  signal?: AbortSignal,
) => {
  return orvalInstance<ListFindings200>({
    url: `/objects/${objectId}/findings`,
    method: 'GET',
    params,
    signal,
  })
}

export const getListFindingsQueryKey = (objectId?: string, params?: ListFindingsParams) => {
  return [`/objects/${objectId}/findings`, ...(params ? [params] : [])] as const
}

export const getListFindingsQueryOptions = <
  TData = Awaited<ReturnType<typeof listFindings>>,
  TError = NotFoundResponse,
>(
  objectId: string,
  params?: ListFindingsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listFindings>>, TError, TData>>
  },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getListFindingsQueryKey(objectId, params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listFindings>>> = ({ signal }) =>
    listFindings(objectId, params, signal)

  return { queryKey, queryFn, enabled: !!objectId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listFindings>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListFindingsQueryResult = NonNullable<Awaited<ReturnType<typeof listFindings>>>
export type ListFindingsQueryError = NotFoundResponse

export function useListFindings<
  TData = Awaited<ReturnType<typeof listFindings>>,
  TError = NotFoundResponse,
>(
  objectId: string,
  params: undefined | ListFindingsParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listFindings>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFindings>>,
          TError,
          Awaited<ReturnType<typeof listFindings>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFindings<
  TData = Awaited<ReturnType<typeof listFindings>>,
  TError = NotFoundResponse,
>(
  objectId: string,
  params?: ListFindingsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listFindings>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFindings>>,
          TError,
          Awaited<ReturnType<typeof listFindings>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFindings<
  TData = Awaited<ReturnType<typeof listFindings>>,
  TError = NotFoundResponse,
>(
  objectId: string,
  params?: ListFindingsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listFindings>>, TError, TData>>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Замечания объекта
 */

export function useListFindings<
  TData = Awaited<ReturnType<typeof listFindings>>,
  TError = NotFoundResponse,
>(
  objectId: string,
  params?: ListFindingsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listFindings>>, TError, TData>>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListFindingsQueryOptions(objectId, params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * @summary Массовое изменение статуса замечаний
 */
export const bulkUpdateFindings = (
  bulkUpdateFindingsBody: BulkUpdateFindingsBody,
  signal?: AbortSignal,
) => {
  return orvalInstance<BulkUpdateFindings200>({
    url: `/findings/bulk`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: bulkUpdateFindingsBody,
    signal,
  })
}

export const getBulkUpdateFindingsMutationOptions = <
  TError = ValidationErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof bulkUpdateFindings>>,
    TError,
    { data: BulkUpdateFindingsBody },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof bulkUpdateFindings>>,
  TError,
  { data: BulkUpdateFindingsBody },
  TContext
> => {
  const mutationKey = ['bulkUpdateFindings']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof bulkUpdateFindings>>,
    { data: BulkUpdateFindingsBody }
  > = (props) => {
    const { data } = props ?? {}

    return bulkUpdateFindings(data)
  }

  return { mutationFn, ...mutationOptions }
}

export type BulkUpdateFindingsMutationResult = NonNullable<
  Awaited<ReturnType<typeof bulkUpdateFindings>>
>
export type BulkUpdateFindingsMutationBody = BulkUpdateFindingsBody
export type BulkUpdateFindingsMutationError = ValidationErrorResponse

/**
 * @summary Массовое изменение статуса замечаний
 */
export const useBulkUpdateFindings = <TError = ValidationErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof bulkUpdateFindings>>,
      TError,
      { data: BulkUpdateFindingsBody },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof bulkUpdateFindings>>,
  TError,
  { data: BulkUpdateFindingsBody },
  TContext
> => {
  const mutationOptions = getBulkUpdateFindingsMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Замечание
 */
export const getFinding = (findingId: string, signal?: AbortSignal) => {
  return orvalInstance<Finding>({ url: `/findings/${findingId}`, method: 'GET', signal })
}

export const getGetFindingQueryKey = (findingId?: string) => {
  return [`/findings/${findingId}`] as const
}

export const getGetFindingQueryOptions = <
  TData = Awaited<ReturnType<typeof getFinding>>,
  TError = NotFoundResponse,
>(
  findingId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFinding>>, TError, TData>>
  },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetFindingQueryKey(findingId)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getFinding>>> = ({ signal }) =>
    getFinding(findingId, signal)

  return { queryKey, queryFn, enabled: !!findingId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getFinding>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFindingQueryResult = NonNullable<Awaited<ReturnType<typeof getFinding>>>
export type GetFindingQueryError = NotFoundResponse

export function useGetFinding<
  TData = Awaited<ReturnType<typeof getFinding>>,
  TError = NotFoundResponse,
>(
  findingId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFinding>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFinding>>,
          TError,
          Awaited<ReturnType<typeof getFinding>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFinding<
  TData = Awaited<ReturnType<typeof getFinding>>,
  TError = NotFoundResponse,
>(
  findingId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFinding>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFinding>>,
          TError,
          Awaited<ReturnType<typeof getFinding>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFinding<
  TData = Awaited<ReturnType<typeof getFinding>>,
  TError = NotFoundResponse,
>(
  findingId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFinding>>, TError, TData>>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Замечание
 */

export function useGetFinding<
  TData = Awaited<ReturnType<typeof getFinding>>,
  TError = NotFoundResponse,
>(
  findingId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFinding>>, TError, TData>>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetFindingQueryOptions(findingId, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Меняет статус и/или комментарий. При отклонении (`dismissed`) комментарий обязателен.
Каждое изменение записывается в историю.

 * @summary Решение инженера по замечанию
 */
export const updateFinding = (findingId: string, findingUpdate: FindingUpdate) => {
  return orvalInstance<Finding>({
    url: `/findings/${findingId}`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: findingUpdate,
  })
}

export const getUpdateFindingMutationOptions = <
  TError = NotFoundResponse | ValidationErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateFinding>>,
    TError,
    { findingId: string; data: FindingUpdate },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateFinding>>,
  TError,
  { findingId: string; data: FindingUpdate },
  TContext
> => {
  const mutationKey = ['updateFinding']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateFinding>>,
    { findingId: string; data: FindingUpdate }
  > = (props) => {
    const { findingId, data } = props ?? {}

    return updateFinding(findingId, data)
  }

  return { mutationFn, ...mutationOptions }
}

export type UpdateFindingMutationResult = NonNullable<Awaited<ReturnType<typeof updateFinding>>>
export type UpdateFindingMutationBody = FindingUpdate
export type UpdateFindingMutationError = NotFoundResponse | ValidationErrorResponse

/**
 * @summary Решение инженера по замечанию
 */
export const useUpdateFinding = <
  TError = NotFoundResponse | ValidationErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateFinding>>,
      TError,
      { findingId: string; data: FindingUpdate },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateFinding>>,
  TError,
  { findingId: string; data: FindingUpdate },
  TContext
> => {
  const mutationOptions = getUpdateFindingMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary История изменений замечания
 */
export const getFindingHistory = (findingId: string, signal?: AbortSignal) => {
  return orvalInstance<FindingHistoryEntry[]>({
    url: `/findings/${findingId}/history`,
    method: 'GET',
    signal,
  })
}

export const getGetFindingHistoryQueryKey = (findingId?: string) => {
  return [`/findings/${findingId}/history`] as const
}

export const getGetFindingHistoryQueryOptions = <
  TData = Awaited<ReturnType<typeof getFindingHistory>>,
  TError = NotFoundResponse,
>(
  findingId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFindingHistory>>, TError, TData>>
  },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetFindingHistoryQueryKey(findingId)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getFindingHistory>>> = ({ signal }) =>
    getFindingHistory(findingId, signal)

  return { queryKey, queryFn, enabled: !!findingId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getFindingHistory>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFindingHistoryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFindingHistory>>
>
export type GetFindingHistoryQueryError = NotFoundResponse

export function useGetFindingHistory<
  TData = Awaited<ReturnType<typeof getFindingHistory>>,
  TError = NotFoundResponse,
>(
  findingId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFindingHistory>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFindingHistory>>,
          TError,
          Awaited<ReturnType<typeof getFindingHistory>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFindingHistory<
  TData = Awaited<ReturnType<typeof getFindingHistory>>,
  TError = NotFoundResponse,
>(
  findingId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFindingHistory>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFindingHistory>>,
          TError,
          Awaited<ReturnType<typeof getFindingHistory>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFindingHistory<
  TData = Awaited<ReturnType<typeof getFindingHistory>>,
  TError = NotFoundResponse,
>(
  findingId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFindingHistory>>, TError, TData>>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary История изменений замечания
 */

export function useGetFindingHistory<
  TData = Awaited<ReturnType<typeof getFindingHistory>>,
  TError = NotFoundResponse,
>(
  findingId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFindingHistory>>, TError, TData>>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetFindingHistoryQueryOptions(findingId, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}
