/**
 * Generated by orval - do not edit manually
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type { Error, NotFoundResponse, Report, ReportCreate } from './model'

import { orvalInstance } from './orval-mutator'

/**
 * @summary Сформировать отчёт по пакету
 */
export const createReport = (
  packageId: string,
  reportCreate: ReportCreate,
  signal?: AbortSignal,
) => {
  return orvalInstance<Report>({
    url: `/packages/${packageId}/reports`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: reportCreate,
    signal,
  })
}

export const getCreateReportMutationOptions = <
  TError = NotFoundResponse | Error,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createReport>>,
    TError,
    { packageId: string; data: ReportCreate },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof createReport>>,
  TError,
  { packageId: string; data: ReportCreate },
  TContext
> => {
  const mutationKey = ['createReport']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createReport>>,
    { packageId: string; data: ReportCreate }
  > = (props) => {
    const { packageId, data } = props ?? {}

    return createReport(packageId, data)
  }

  return { mutationFn, ...mutationOptions }
}

export type CreateReportMutationResult = NonNullable<Awaited<ReturnType<typeof createReport>>>
export type CreateReportMutationBody = ReportCreate
export type CreateReportMutationError = NotFoundResponse | Error

/**
 * @summary Сформировать отчёт по пакету
 */
export const useCreateReport = <TError = NotFoundResponse | Error, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createReport>>,
      TError,
      { packageId: string; data: ReportCreate },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createReport>>,
  TError,
  { packageId: string; data: ReportCreate },
  TContext
> => {
  const mutationOptions = getCreateReportMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Отчёты объекта
 */
export const listReports = (objectId: string, signal?: AbortSignal) => {
  return orvalInstance<Report[]>({ url: `/objects/${objectId}/reports`, method: 'GET', signal })
}

export const getListReportsQueryKey = (objectId?: string) => {
  return [`/objects/${objectId}/reports`] as const
}

export const getListReportsQueryOptions = <
  TData = Awaited<ReturnType<typeof listReports>>,
  TError = NotFoundResponse,
>(
  objectId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listReports>>, TError, TData>>
  },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getListReportsQueryKey(objectId)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listReports>>> = ({ signal }) =>
    listReports(objectId, signal)

  return { queryKey, queryFn, enabled: !!objectId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listReports>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListReportsQueryResult = NonNullable<Awaited<ReturnType<typeof listReports>>>
export type ListReportsQueryError = NotFoundResponse

export function useListReports<
  TData = Awaited<ReturnType<typeof listReports>>,
  TError = NotFoundResponse,
>(
  objectId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listReports>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listReports>>,
          TError,
          Awaited<ReturnType<typeof listReports>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListReports<
  TData = Awaited<ReturnType<typeof listReports>>,
  TError = NotFoundResponse,
>(
  objectId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listReports>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listReports>>,
          TError,
          Awaited<ReturnType<typeof listReports>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListReports<
  TData = Awaited<ReturnType<typeof listReports>>,
  TError = NotFoundResponse,
>(
  objectId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listReports>>, TError, TData>>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Отчёты объекта
 */

export function useListReports<
  TData = Awaited<ReturnType<typeof listReports>>,
  TError = NotFoundResponse,
>(
  objectId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listReports>>, TError, TData>>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListReportsQueryOptions(objectId, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * @summary Отчёт
 */
export const getReport = (reportId: string, signal?: AbortSignal) => {
  return orvalInstance<Report>({ url: `/reports/${reportId}`, method: 'GET', signal })
}

export const getGetReportQueryKey = (reportId?: string) => {
  return [`/reports/${reportId}`] as const
}

export const getGetReportQueryOptions = <
  TData = Awaited<ReturnType<typeof getReport>>,
  TError = NotFoundResponse,
>(
  reportId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getReport>>, TError, TData>>
  },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetReportQueryKey(reportId)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getReport>>> = ({ signal }) =>
    getReport(reportId, signal)

  return { queryKey, queryFn, enabled: !!reportId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getReport>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetReportQueryResult = NonNullable<Awaited<ReturnType<typeof getReport>>>
export type GetReportQueryError = NotFoundResponse

export function useGetReport<
  TData = Awaited<ReturnType<typeof getReport>>,
  TError = NotFoundResponse,
>(
  reportId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getReport>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReport>>,
          TError,
          Awaited<ReturnType<typeof getReport>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReport<
  TData = Awaited<ReturnType<typeof getReport>>,
  TError = NotFoundResponse,
>(
  reportId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getReport>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReport>>,
          TError,
          Awaited<ReturnType<typeof getReport>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReport<
  TData = Awaited<ReturnType<typeof getReport>>,
  TError = NotFoundResponse,
>(
  reportId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getReport>>, TError, TData>>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Отчёт
 */

export function useGetReport<
  TData = Awaited<ReturnType<typeof getReport>>,
  TError = NotFoundResponse,
>(
  reportId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getReport>>, TError, TData>>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetReportQueryOptions(reportId, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * @summary Скачать PDF отчёта
 */
export const downloadReport = (reportId: string, signal?: AbortSignal) => {
  return orvalInstance<Blob>({
    url: `/reports/${reportId}/download`,
    method: 'GET',
    responseType: 'blob',
    signal,
  })
}

export const getDownloadReportQueryKey = (reportId?: string) => {
  return [`/reports/${reportId}/download`] as const
}

export const getDownloadReportQueryOptions = <
  TData = Awaited<ReturnType<typeof downloadReport>>,
  TError = NotFoundResponse | Error,
>(
  reportId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadReport>>, TError, TData>>
  },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getDownloadReportQueryKey(reportId)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadReport>>> = ({ signal }) =>
    downloadReport(reportId, signal)

  return { queryKey, queryFn, enabled: !!reportId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof downloadReport>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DownloadReportQueryResult = NonNullable<Awaited<ReturnType<typeof downloadReport>>>
export type DownloadReportQueryError = NotFoundResponse | Error

export function useDownloadReport<
  TData = Awaited<ReturnType<typeof downloadReport>>,
  TError = NotFoundResponse | Error,
>(
  reportId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadReport>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadReport>>,
          TError,
          Awaited<ReturnType<typeof downloadReport>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadReport<
  TData = Awaited<ReturnType<typeof downloadReport>>,
  TError = NotFoundResponse | Error,
>(
  reportId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadReport>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadReport>>,
          TError,
          Awaited<ReturnType<typeof downloadReport>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadReport<
  TData = Awaited<ReturnType<typeof downloadReport>>,
  TError = NotFoundResponse | Error,
>(
  reportId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadReport>>, TError, TData>>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Скачать PDF отчёта
 */

export function useDownloadReport<
  TData = Awaited<ReturnType<typeof downloadReport>>,
  TError = NotFoundResponse | Error,
>(
  reportId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadReport>>, TError, TData>>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getDownloadReportQueryOptions(reportId, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}
